Mobile View
XsidX/my-portfolio pull request #2
Opened 2022-05-26 19:09 UTC by XsidX

-Add projects and about section to mobile view
-Fix header background

2022-05-26 19:50 UTC, Munsa1 requested changes
Hi @XsidX , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, for the `mobile version` review which was supposed to be submitted on day 2 titled `setup`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-26 20:05 UTC, XsidX commented
Hello @Munsa1 
What do you mean, *which was supposed to be submitted on day 2 titled setup*, should I rename this pull request? Because they only have similar names but are totally different.

2022-05-27 09:48 UTC, bellom commented
@XsidX  - Looking into it, hang in there.

CR Leader.

2022-05-27 10:04 UTC, XsidX commented
> @XsidX - Looking into it, hang in there.
> 
> CR Leader.

Perfect...

2022-05-27 10:07 UTC, bellom commented
@XsidX - I noticed you already have mobile-view approved, can you please use the right milestone name, and also can you tell me the name of the current milestone on your dashboard.

2022-05-27 10:17 UTC, XsidX commented
> @XsidX - I noticed you already have mobile-view approved, can you please use the right milestone name, and also can you tell me the name of the current milestone on your dashboard.

Oh, I see
Current milestone name: [Portfolio: mobile version]

2022-05-27 10:20 UTC, bellom commented
Yes, please.

What was the name of the previous milestone that was approved on your dashboard?

2022-05-27 10:22 UTC, XsidX commented
> Yes, please.
> 
> What was the name of the previous milestone that was approved on your dashboard?

The previous milestone was: [Portfolio: setup and mobile version skeleton]

2022-05-27 10:33 UTC, sinansevgi reviewed
Hello, @XsidX  👋,

_This is an additional review as a result of the second opinion request._

Since the name of this milestone is `Portfolio: mobile version`, I think your PR title is well descriptive and you can use it. Since you still have review limits left, please ask for another review in your Dashboard, and the next Code Reviewer will leave a **review** for your project.

Keep rocking 🚀!

2022-05-27 10:36 UTC, XsidX commented
> Hello, @XsidX 👋,
> 
> _This is an additional review as a result of the second opinion request._
> 
> Since the name of this milestone is `Portfolio: mobile version`, I think your PR title is well descriptive and you can use it. Since you still have review limits left, please ask for another review in your Dashboard, and the next Code Reviewer will leave a **review** for your project.
> 
> Keep rocking 🚀!

Great, thank you. I already did that.

2022-05-27 11:14 UTC, phelian23 requested changes
Hi @XsidX, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✅ Correct use of Github Flow
✅ Good commit messages
✅ Good README template

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 11:14 UTC, phelian23 commented on styles.css
> +.project-container h2 {
- [ ] Kindly add appropriate margins between the sections, and also between each project cards
Your designs
![Capture](https://user-images.githubusercontent.com/85095702/170688595-9a1eb1f3-0119-470a-9b20-c1c84515f550.jpg)
![Capture1](https://user-images.githubusercontent.com/85095702/170688636-49f3b655-f29e-49e6-98b5-2753c295e780.jpg)
![Capture2](https://user-images.githubusercontent.com/85095702/170688736-a2e1659b-31e1-4e47-9ff7-2af503eebcce.jpg)
Figma Designs
![figma](https://user-images.githubusercontent.com/85095702/170688793-be0b6ff2-8aed-4d6e-b442-05502b0018ce.jpg)
![figma2](https://user-images.githubusercontent.com/85095702/170688819-3795f892-bc16-49e3-a89e-a3b0502e6aaf.jpg)
![figma3](https://user-images.githubusercontent.com/85095702/170688833-dd6226b7-5b75-4cf3-b857-808d3929d1b7.jpg)

2022-05-27 13:44 UTC, vic778 approved these changes
## Hi @XsidX   , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Charlie Brown](https://media.giphy.com/media/ZdO4NenDbsQNwUwKDB/giphy.gif)

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-05-27 13:50 UTC, merged